### PR TITLE
restructured docs into v3 and added arb. policies

### PR DESCRIPTION
**Pull request by b3nedictvs**

### CODE REVIEW

**Comment by b3nedictvs** [comment]
@plor how can I add a reviewer?

**Comment by plor** [comment]
> @plor how can I add a reviewer?
it is in the reviewers menu in the PR

**Comment by plor** [comment]
Why is it restructured as v3?

**Comment by b3nedictvs** [comment]
> Why is it restructured as v3?

There are several reasons for that.

1. The documentation hierarchy in v.2 would have made integrating the arbitration policy confusing because it didn't really fit anywhere.

2. I had to introduce an introduction page to the arbitration policy section, as arb. infrastructure and the policies belong together but are different.

3. 2-3 community calls back we discussed the need for updating the documentation and it appeared to make sense to prepare for this by applying the structure of intro + documentation pages consistently throughout the documentation.


If you disagree, I don't mind structuring it in v.2.

**Comment by plor** [comment]
> > Why is it restructured as v3?
> 
> There are several reasons for that.
> 
> 1. The documentation hierarchy in v.2 would have made integrating the arbitration policy confusing because it didn't really fit anywhere.
> 2. I had to introduce an introduction page to the arbitration policy section, as arb. infrastructure and the policies belong together but are different.
> 3. 2-3 community calls back we discussed the need for updating the documentation and it appeared to make sense to prepare for this by applying the structure of intro + documentation pages consistently throughout the documentation.
> 
> If you disagree, I don't mind structuring it in v.2.

I think it is fine, I'm just not a fan of versioning via naming over using version control as it is meant. I will defer to @geovgy who set this docs site up in the first place. I'm not very familiar with the best approach here.

**Comment by b3nedictvs** [comment]
I'm with you, I just know that the way these docs work is that you have to create an index, which I am not sure of how to do. So guidance would be appreciated, but @memosys agreed to take on some of the arbitration implementation work on the frontend. I think he could help once we know what to do.

**Comment by wtfsayo** [comment]
Just gonna check why the build is not working, fix that and merge it!

**Comment by wtfsayo** [comment]
@benedictvscriticus do you mean to overwrite previous docs here and just keep v3 ?

**Pull request merged**
